version: "3.9"
services:
  server:
    build: .
    ports:
      - "5000:3001"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DOCKER_DB_PASS}"
      POSTGRES_USER: "docker"
    volumes:
      - data:/var/lib/postgresql/data
